# This file was automatically generated by APIMATIC BETA v2.0 on 03/05/2016
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'apimatic_calculator/api_helper.rb'
require 'apimatic_calculator/api_exception.rb'
require 'apimatic_calculator/configuration.rb'

# Controllers
require 'apimatic_calculator/controllers/simple_calculator_controller.rb'

# Models
require 'apimatic_calculator/models/operation_type_enum.rb'
require 'apimatic_calculator/models/base_string_enum.rb'
