# This file was automatically generated by APIMATIC BETA v2.0 on 03/05/2016

require 'apimatic_calculator/models/base_string_enum'

module ApimaticCalculator
  class OperationTypeEnum < BaseStringEnum

    # Represents the sum operator
    enum_attr :SUM, 'SUM'

    # Represents the subtract operator
    enum_attr :SUBTRACT, 'SUBTRACT'

    # Represents the multiply operator
    enum_attr :MULTIPLY, 'MULTIPLY'

    # Represents the divide operator
    enum_attr :DIVIDE, 'DIVIDE'

  end
end